version: "3"
services:
  web: 
    build: 
      context: . 
      dockerfile: Dockerfile
    container_name: web
    restart: unless-stopped
    volumes:
      - ./:/app
    ports:
      - 3000:3000

